### ISSUE TITLE
Error creating the dataset

### ISSUE THREAD

**Issue by mikelewis0** [complementizer/wcep-mds-dataset#1] opened 2020-05-26 21:29 UTC
Hi, I'm trying to follow the steps in the README to create the dataset. The first two steps seemed to work ok, but then I hit this error in combine_and_split. Can you tell me how to fix this?

350000 cc articles done, 2677/10200 clusters done
360000 cc articles done, 2706/10200 clusters done
Traceback (most recent call last):
  File "combine_and_split.py", line 127, in <module>
    main(parser.parse_args())
  File "combine_and_split.py", line 109, in main
    clusters, args.cc_articles, id_to_cluster_idx, tmp_clusters_path
  File "combine_and_split.py", line 38, in add_cc_articles_to_clusters
    c.setdefault('cc_articles_filled', [])
AttributeError: 'NoneType' object has no attribute 'setdefault'

**Comment by complementizer** [comment] 2020-05-28 09:09
Will look into this ASAP!

**Comment by complementizer** [comment] 2020-05-28 14:22
Not 100% sure still why your error was caused, probably due to an article from Common Crawl stored multiple times. I reproduced it only by inserting duplicate articles in `data/cc_storage/cc_articles.jsonl`. I made some changes in `combine_and_split.py` that should prevent that bug in such a case. Also found another bug in `combine_and_split.py` (only if `--max-cluster-size` was used before). Let me know if that fixes it for you.

**Comment by shahbazsyed** [comment] 2020-06-01 17:55
I get this error on the first step

<pre>Traceback (most recent call last):
  File &quot;extract_wcep_articles.py&quot;, line 142, in &lt;module&gt;
    main(parser.parse_args())
  File &quot;extract_wcep_articles.py&quot;, line 118, in main
    write_jsonl(articles, outpath, mode=&apos;a&apos;)
NameError: name &apos;write_jsonl&apos; is not defined
</pre>

**Comment by complementizer** [comment] 2020-06-01 19:59
> I get this error on the first step
> 
> Traceback (most recent call last):
>   File "extract_wcep_articles.py", line 142, in <module>
>     main(parser.parse_args())
>   File "extract_wcep_articles.py", line 118, in main
>     write_jsonl(articles, outpath, mode='a')
> NameError: name 'write_jsonl' is not defined

Is fixed now.

**Closed as completed** 2020-10-06 12:44 UTC
